packages:
  - packages/*

autoInstallPeers: false

dedupePeerDependents: false

engineStrict: true

onlyBuiltDependencies:
  - '@vscode/vsce-sign'
  - keytar

patchedDependencies:
  '@vscode/vsce@3.7.1': patches/@vscode__vsce@3.7.1.patch

resolvePeersFromWorkspaceRoot: false

strictPeerDependencies: true

updateNotifier: false

workspaceConcurrency: 0
